#Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false

script:
  - julia -e 'Pkg.add("Conda")'
  - LD_PRELOAD=${HOME}/.julia/v0.6/Conda/deps/usr/lib/libz.so julia -e 'Pkg.clone(pwd());Pkg.test("ClimateTools"; coverage=true);'
  - julia -e 'Pkg.add("PyCall")'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall")'
  - julia -e 'using Conda; Conda.add("matplotlib")'
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Qlab")'
  - julia --check-bounds=yes -e 'Pkg.test("Qlab", coverage=true)'
